### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by NorbiPeti** [TBMCPlugins/ButtonWebsiteModule#8]
Auto-obtaining is broken.

```
[12:01:50] [Craft Scheduler Thread - 12/INFO]: [ButtonWebsiteModule] Starting webserver...
[12:01:50] [Craft Scheduler Thread - 12/INFO]: Starting up...
[12:01:50] [Craft Scheduler Thread - 12/INFO]: Loading account from file
[12:01:51] [Craft Scheduler Thread - 12/ERROR]: Failed to get a certificate for domains [server.figytuna.com]
org.shredzone.acme4j.exception.AcmeNetworkException: Network error
	at org.shredzone.acme4j.connector.DefaultConnection.sendRequest(DefaultConnection.java:112) ~[ButtonWebsiteModule-master-SNAPSHOT.jar:?]
	at org.shredzone.acme4j.provider.AbstractAcmeProvider.directory(AbstractAcmeProvider.java:55) ~[ButtonWebsiteModule-master-SNAPSHOT.jar:?]
	at org.shredzone.acme4j.Session.readDirectory(Session.java:211) ~[ButtonWebsiteModule-master-SNAPSHOT.jar:?]
	at org.shredzone.acme4j.Session.resourceUri(Session.java:186) ~[ButtonWebsiteModule-master-SNAPSHOT.jar:?]
	at org.shredzone.acme4j.Registration.authorizeDomain(Registration.java:188) ~[ButtonWebsiteModule-master-SNAPSHOT.jar:?]
	at buttondevteam.website.AcmeClient.authorize(AcmeClient.java:196) ~[ButtonWebsiteModule-master-SNAPSHOT.jar:?]
	at buttondevteam.website.AcmeClient.fetchCertificate(AcmeClient.java:89) ~[ButtonWebsiteModule-master-SNAPSHOT.jar:?]
	at buttondevteam.website.AcmeClient.main(AcmeClient.java:317) ~[ButtonWebsiteModule-master-SNAPSHOT.jar:?]
	at buttondevteam.website.ButtonWebsiteModule.lambda$onEnable$1(ButtonWebsiteModule.java:137) ~[ButtonWebsiteModule-master-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[?:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1964) ~[?:1.8.0_171]
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:328) ~[?:1.8.0_171]
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:322) ~[?:1.8.0_171]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1614) ~[?:1.8.0_171]
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216) ~[?:1.8.0_171]
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052) ~[?:1.8.0_171]
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:987) ~[?:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072) ~[?:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385) ~[?:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413) ~[?:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397) ~[?:1.8.0_171]
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559) ~[?:1.8.0_171]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) ~[?:1.8.0_171]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162) ~[?:1.8.0_171]
	at org.shredzone.acme4j.connector.DefaultConnection.sendRequest(DefaultConnection.java:108) ~[ButtonWebsiteModule-master-SNAPSHOT.jar:?]
	... 13 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397) ~[?:1.8.0_171]
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302) ~[?:1.8.0_171]
	at sun.security.validator.Validator.validate(Validator.java:260) ~[?:1.8.0_171]
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324) ~[?:1.8.0_171]
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229) ~[?:1.8.0_171]
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124) ~[?:1.8.0_171]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1596) ~[?:1.8.0_171]
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216) ~[?:1.8.0_171]
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052) ~[?:1.8.0_171]
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:987) ~[?:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072) ~[?:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385) ~[?:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413) ~[?:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397) ~[?:1.8.0_171]
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559) ~[?:1.8.0_171]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) ~[?:1.8.0_171]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162) ~[?:1.8.0_171]
	at org.shredzone.acme4j.connector.DefaultConnection.sendRequest(DefaultConnection.java:108) ~[ButtonWebsiteModule-master-SNAPSHOT.jar:?]
	... 13 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141) ~[?:1.8.0_171]
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126) ~[?:1.8.0_171]
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280) ~[?:1.8.0_171]
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392) ~[?:1.8.0_171]
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302) ~[?:1.8.0_171]
	at sun.security.validator.Validator.validate(Validator.java:260) ~[?:1.8.0_171]
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324) ~[?:1.8.0_171]
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229) ~[?:1.8.0_171]
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124) ~[?:1.8.0_171]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1596) ~[?:1.8.0_171]
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216) ~[?:1.8.0_171]
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052) ~[?:1.8.0_171]
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:987) ~[?:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072) ~[?:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385) ~[?:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413) ~[?:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397) ~[?:1.8.0_171]
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559) ~[?:1.8.0_171]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) ~[?:1.8.0_171]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162) ~[?:1.8.0_171]
	at org.shredzone.acme4j.connector.DefaultConnection.sendRequest(DefaultConnection.java:108) ~[ButtonWebsiteModule-master-SNAPSHOT.jar:?]
	... 13 more
[12:01:51] [Craft Scheduler Thread - 12/INFO]: [ButtonWebsiteModule] Webserver started
```

**Comment by NorbiPeti** [comment]
This was fixed before Update 4, but whatever.
